/**
 * Created by chzellot on 06.02.17.
 */

export const REPLAY = {
    START: 'REPLAY_START',
    STOP: 'REPLAY_STOP',
};

export const RECORDING = {
    START: 'RECORDING_START',
    STOP: 'RECORDING_STOP'
};

export const ACTION_POSITION = {
    MOVE: 'CURSOR_MOVE',
    CLICK: 'CURSOR_CLICK',
};

export const CANVAS = {
    DRAWING: 'CANVAS_DRAWING',
    MOUSE_DOWN: 'CANVAS_MOUSE_DOWN',
    MOUSE_UP: 'CANVAS_MOUSE_UP',
    MOUSE_MOVE: 'CANVAS_MOUSE_MOVE',
    CHANGE_COLOR: 'CHANGE_COLOR',
    DRAWN: 'CANVAS_DRAWN'
};